### DISCUSSION TITLE
Caching - container job [Gradle]

### DISCUSSION THREAD

**Discussion by Adirsellam** [burrunan/gradle-cache-action#54] [Q&A]
Hi,
I try to use the action for caching inside a job running inside a container.
I use the following configuration:
```
- uses: burrunan/gradle-cache-action@v1
        name: Build PROJECT_NAME
        with:
          arguments: |
            clean build -i
            --build-cache
          remote-build-cache-proxy-enabled: false
          save-local-build-cache: true
          execution-only-caches: true
          save-generated-gradle-jars: false
          save-maven-dependencies-cache: false
          concurrent: true
          gradle-build-scan-report: false
```
Output I get:
```
Cache was not found for 1-index-gradle-build-cache-Linux--gradle-7.1-defaultbranch-efe7681f082a1919e914cd2837700e3575e18fa8
, restore keys: 1-index-gradle-build-cache-Linux--gradle-7.1-defaultbranch, 1-index-gradle-build-cache-Linux--gradle-7.1-master, 1-index-gradle-build-cache-Linux--gradle-7.1-main
Cache restore took 0 seconds
```
I couldn't get to a point where the caching works.
Would love to get some help If anyone has come across this before.
