### ISSUE TITLE
Support executing multiple Gradle (or shell?) commands

### ISSUE THREAD

**Issue by vlsi** [burrunan/gradle-cache-action#17]
Sample use case:

```yaml
    - name: 'Run tests with JaCoCo'
      shell: bash
      run: |
        ./gradlew --version
        ./gradlew --scan --no-parallel --stacktrace --warning-mode=all -PenableJaCoCo build jacocoRootReport
```
