### ISSUE TITLE
What's exactly `cache-only` mode?

### ISSUE THREAD

**Issue by wzieba** [burrunan/gradle-cache-action#23]
In the documentation I can see that there are two ways to use this action.

### 1. As wrapper around gradle command:
```yml
name: Build
on: [push]
jobs:
  check_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: burrunan/gradle-cache-action@v1.5
        with:
          arguments: assemble
```

### 2. As a separate step
```yml
name: Build
on: [push]
jobs:
  check_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: burrunan/gradle-cache-action@v1.5
      - run: ./gradlew assemble
```

I can see in [Sample integration](https://github.com/burrunan/gradle-cache-action#sample-integrations) that the first one is preferable but in [Can I use the caching part of the action only](https://github.com/burrunan/gradle-cache-action#can-i-use-the-caching-part-of-the-action-only) there is mentioned `cache-only` mode. To what "cache" does the `cache-only` refers to? Is it only `dependency cache` and not `build cache` ?

I've done some tests in sample repo:
#### 1. Wrapper around gradle command *does* perform `build cache`: 
[55 actionable tasks: 13 executed, 42 from cache](https://github.com/wzieba/BasicAndriodApp/runs/1166155100?check_suite_focus=true#step:4:449)

#### 2. Seperate step *does not* perform `build cache`
[55 actionable tasks: 55 executed](https://github.com/wzieba/BasicAndriodApp/runs/1166153438?check_suite_focus=true#step:5:104)
