### ISSUE TITLE
No Cache is stored because nothing has been found

### ISSUE THREAD

**Issue by eye2web** [burrunan/gradle-cache-action#41]
Im getting to following messages during the POST step.
I'm using version 1.10

`
Save gradle-generated-jars
  gradle-generated-jars: no files to cache => won't upload empty cache
Save dependencies-gradle
  dependencies-gradle: creating single-layer cache image
  dependencies-gradle: no files to cache => won't upload empty cache
Save dependencies-maven
  dependencies-maven: creating single-layer cache image
  dependencies-maven: no files to cache => won't upload empty cache
`

**Comment by mcarrillowz** [comment]
I'm having the same issue, @eye2web do you find a way to solve it?

I'm using the action like this:

```
      - uses: burrunan/gradle-cache-action@v1
        name: Test Coverage
        with:
          read-only: false
          arguments: :project:unitTestCoverageVerificationDebug
          concurrent: false
          gradle-build-scan-report: false
```
