### ISSUE TITLE
Unable to use action inside a self-hosted runner

### ISSUE THREAD

**Issue by braedongough** [burrunan/gradle-cache-action#44]
We're currently in the process of migrating to a self-hosted runner setup. We've been actively using `1.10` in our workflows for months without a problem with Github-hosted runners. 

When trying to run this action inside of our self-hosted runners we receive the following error: 
```
Error: ~/.gradle-cache-action/layer-dependencies-gradle.json is not found
```

Downgrading the action to `1.9` resolved the above error and we were able to run the workflow without issue in our branch, however, when we merged into our default branch, the action failed with the same error.  

Our current self-hosted runner image is fairly bare-bones. We're extending the [`summerwind/actions-runner`](https://github.com/actions-runner-controller/actions-runner-controller#software-installed-in-the-runner-image) only to add `node` and `kubectl`, relying on setup actions for other necessary dependencies, primarily `actions/setup-java@v2.1.0` in this case. 

For reference, this is how we're using the action in one place: 

```yaml
      - name: Gradle Build
        uses: burrunan/gradle-cache-action@v1.10
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          arguments: build -x test
          gradle-version: wrapper
          save-local-build-cache: ${{ github.ref == env.default_branch_ref }}
          save-generated-gradle-jars: ${{ github.ref == env.default_branch_ref }}
```

Are you aware of any necessary dependencies that must be present on the runner for us to leverage this action? We're pretty stumped on this one! 

Here's a gist of the complete output including debug logs for this step: 
https://gist.github.com/braedongough/4aa7aa6311d8caad7470c0512f70b9ab
